### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by brandleesee** [team-phoenix/Phoenix.vg#3]
Continuation of this issue: https://github.com/team-phoenix/Phoenix/issues/324

## http://phoenix.vg

![screenshot from 2016-12-16 22-13-46](https://cloud.githubusercontent.com/assets/12674437/21278725/16dff274-c3dd-11e6-84f8-21f89e2a4336.png)

## https://phoenix.vg

![screenshot from 2016-12-16 22-14-36](https://cloud.githubusercontent.com/assets/12674437/21278727/16e46dc2-c3dd-11e6-8cc3-ecf95832f678.png)

**Comment by athairus** [comment]
Let's keep this on the main project, this issues page isn't really for webserver issues.
